import type { CardParts } from "@/lib/cards/present";
import BOOTH_DATA from "~/data/booth-data.json";

export type BoothData = {
  investigation: {
    role: string;
    ranAt: string;
    looked: string;
    checked: number;
    trace: { tool: string; label: string; summary: string }[];
    story: { kind: string; scope: string; finding: string; ruledOut: string[]; action: string | null };
    card: CardParts;
  };
  chips: { role: string; items: { label: string; reason: string }[] };
  memory: { role: string; title: string; learning: string; confirm: string; facts: { type: string; value: string; seen: number }[] };
  suggestion: { role: string; badge: string; reason: string; keep: string; source: string; card: CardParts };
  anomaly: { role: string; scope: string; severity: string; observed: string; expected: string; gap: string; hypothesis: string; lesson: string | null; card: CardParts };
  forecast: { role: string; card: CardParts };
};

/** Real app data for the booth cuts, generated by `bun run site:booth-data`. */
export const BOOTH = BOOTH_DATA as unknown as BoothData;
