import { DEFAULT_LABELS, type ChatLabels, type ChatToolState } from "vexa/chat";
import { TH } from "@/lib/i18n/th";

const TOOL_STATES: Record<ChatToolState, string> = {
  "input-streaming": "กำลังเตรียมข้อมูล",
  "input-available": "กำลังดึงข้อมูล",
  "approval-requested": "รอการอนุมัติ",
  "approval-responded": "ตอบกลับแล้ว",
  "output-available": "เสร็จแล้ว",
  "output-denied": "ถูกปฏิเสธ",
  "output-error": "เกิดข้อผิดพลาด",
};

export const WINYU_CHAT_LABELS: ChatLabels = {
  ...DEFAULT_LABELS,
  emptyTitle: TH.chat.emptyTitle,
  emptyDescription: TH.chat.emptyDescription,
  thinking: TH.chat.thinking,
  unanswered: TH.chat.unanswered,
  reasoning: "ความคิด",
  thoughtFor: (seconds) => `คิดอยู่ ${seconds} วินาที`,
  steps: (count) => `${count} ขั้นตอน`,
  approveTool: (tool) => `อนุมัติให้ใช้ ${tool} ไหม`,
  approved: "อนุมัติแล้ว",
  rejected: "ปฏิเสธแล้ว",
  approve: TH.chat.approve,
  reject: TH.chat.reject,
  runOnPage: (tool) => `เรียกใช้ ${tool} บนหน้านี้ไหม`,
  runSteps: (count) => `ทำ ${count} ขั้นตอนบนหน้านี้ไหม`,
  run: "ทำเลย",
  cancel: TH.common.cancel,
  restore: "ย้อนกลับมาตรงนี้",
  restoreTooltip: "ย้อนบทสนทนากลับมาที่จุดนี้",
  startOver: TH.chat.startOver,
  closeChat: TH.common.close,
  openAssistant: "เปิด Winyu",
  closeAssistant: "ปิด Winyu",
  queued: "รอส่ง",
  removeQueued: "เอาออกจากคิว",
  sentWithAttachments: "ส่งพร้อมไฟล์แนบ",
  attachment: "ไฟล์แนบ",
  securityTitle: "พบข้อความน่าสงสัยในข้อมูลจากเครื่องมือ",
  securityBody: (tool) => `ข้อมูลจาก ${tool} มีคำสั่งที่พยายามสั่งงานผู้ช่วย ระบบข้ามคำสั่งนั้นและปิดเครื่องมือที่เปลี่ยนข้อมูลในคำตอบนี้`,
  placeholder: TH.landing.composerPlaceholder,
  send: TH.chat.send,
  stop: TH.chat.stop,
  attach: "แนบไฟล์",
  addAttachment: "เพิ่มรูปหรือไฟล์",
  takeScreenshot: "จับภาพหน้าจอ",
  removeAttachment: "เอาไฟล์แนบออก",
  selectModel: TH.chat.selectModel,
  searchModels: "ค้นหาโมเดล",
  noModels: "ไม่พบโมเดล",
  tokenUsage: "การใช้บริบท",
  usageInput: "ขาเข้า",
  usageOutput: "ขาออก",
  usageReasoning: "การคิด",
  usageCache: "แคช",
  usageTotalCost: "ค่าใช้จ่ายรวม",
  toolInput: "พารามิเตอร์",
  toolOutput: "ผลลัพธ์",
  toolState: (state) => TOOL_STATES[state],
  usedSources: (count) => `ใช้แหล่งข้อมูล ${count} แห่ง`,
};
